namespace VelaShell.Plugin.Mongo;

public sealed partial class Loc
{
    /// <summary>文档编辑器(表单 + 实时预览)与客户端 $jsonSchema 预检。</summary>
    private static readonly (string Key, string En, string Zh)[] DocumentEditorTexts =
    [
        // ── 标题与子标题行 ──
        ("Doc_TitleEdit", "Edit document", "编辑文档"),
        ("Doc_TitleNew", "New document", "新建文档"),
        ("Doc_TitleView", "View document", "查看文档"),
        ("Doc_IdLocked", "_id can't be changed in place — use Save as new", "_id 不可原地修改 · 要换 _id 请用「另存为新文档」"),
        ("Doc_ModeForm", "Form", "表单"),
        ("Doc_ModeJson", "JSON", "JSON"),
        ("Doc_ModeDiff", "Diff", "对比"),
        ("Doc_FindField", "Find field", "查找字段"),
        ("Doc_FindPlaceholder", "Filter fields…", "过滤字段…"),
        ("Doc_Paste", "Paste from clipboard", "从剪贴板粘贴"),
        ("Doc_FillSchema", "Fill missing fields from schema", "按 Schema 补全缺失字段"),

        // ── 表单 ──
        ("Doc_ColField", "Field", "字段"),
        ("Doc_ColType", "Type", "类型"),
        ("Doc_ColValue", "Value", "值"),
        ("Doc_DragHint", "Drag to reorder", "拖动排序"),
        ("Doc_AddSibling", "Add a field after this one", "在下面添加同级字段"),
        ("Doc_AddChild", "Add a child field / item", "添加子字段 / 项"),
        ("Doc_DeleteField", "Delete field", "删除字段"),
        ("Doc_Generate", "Generate", "生成"),
        ("Doc_SetString", "Make it a string", "设为字符串"),
        ("Doc_PickDate", "Pick a date", "选择日期"),
        ("Doc_LocalTime", "Entered in local time; stored as UTC", "按本地时间填写,存为 UTC"),
        ("Doc_Expand", "Expand", "展开"),
        ("Doc_Collapse", "Collapse", "收起"),
        ("Doc_RemoveItem", "Remove item", "删除这一项"),
        ("Doc_WasValue", "Was {0}", "原值 {0}"),
        ("Doc_Revert", "Revert", "还原"),
        ("Doc_EnumHint", "enum: {0}", "enum: {0}"),
        ("Doc_RuleViolation", "Validation rule: {0}", "违反验证规则:{0}"),
        ("Doc_AddField", "Add field", "添加字段"),
        ("Doc_AddFieldHint", "Ctrl+Enter · field names complete from the schema sample", "Ctrl+Enter · 字段名支持补全(来自 Schema 抽样)"),
        ("Doc_SuggestHeader", "Fields in sampled documents", "抽样文档里的字段"),
        ("Doc_KindReset", "{0}: the value couldn't be converted to {1} and was reset", "{0}:值无法换算为 {1},已重置"),
        ("Doc_NameEmpty", "Field name can't be empty", "字段名不能为空"),
        ("Doc_NameDuplicate", "Duplicate field name {0}", "字段名 {0} 重复"),
        ("Doc_NameDollar", "Field names can't start with $", "字段名不能以 $ 开头"),
        ("Doc_NameDot", "Field names can't contain dots", "字段名不能含点号"),
        ("Doc_LiftedProblem", "{0}: {1}", "{0}:{1}"),
        ("Doc_IdChanged", "_id can't be changed or removed — use Save as new", "_id 不能修改或删除 —— 请用「另存为新文档」"),

        // ── JSON 与对比 ──
        ("Doc_JsonError", "JSON: {0}", "JSON 语法错误:{0}"),
        ("Doc_JsonDiscarded", "The JSON had a syntax error; back to the last valid version", "JSON 有语法错误,已回到上一份有效内容"),
        ("Doc_DiffOriginal", "Original", "原文档"),
        ("Doc_DiffCurrent", "Current", "当前"),
        ("Doc_DiffNew", "New document — nothing to compare against", "新文档 · 没有可对比的原文档"),

        // ── 预览与命令 ──
        ("Doc_Preview", "Live preview", "实时预览"),
        ("Doc_CopyDocument", "Copy the document", "复制文档"),
        ("Doc_PreviewItems", "[ …{0} items ]", "[ …{0} 项 ]"),
        ("Doc_Command", "Command to run", "将执行的命令"),
        ("Doc_NoCommand", "// nothing to save", "// 没有要提交的修改"),
        ("Doc_OnlyChanged", "Only changed fields are sent · optimistic concurrency: checks and refreshes updatedAt",
            "仅提交变更字段 · 乐观并发:校验并刷新 updatedAt"),
        ("Doc_OnlyChangedNoVersion", "Only changed fields are sent · matched by _id (no updatedAt to check)",
            "仅提交变更字段 · 按 _id 匹配(文档无 updatedAt,不做并发校验)"),
        ("Doc_ReplaceNote", "Field order changed: the whole document is replaced · checks updatedAt",
            "字段顺序有变:整份替换 · 乐观并发:校验 updatedAt"),
        ("Doc_ReplaceNoteNoVersion", "Field order changed: the whole document is replaced · matched by _id",
            "字段顺序有变:整份替换 · 按 _id 匹配"),
        ("Doc_InsertNote", "Inserts a new document · _id is generated when absent", "插入一份新文档 · 没有 _id 时由驱动生成"),

        // ── 底栏 ──
        ("Doc_CountModified", "{0} changed", "{0} 处修改"),
        ("Doc_CountAdded", "{0} new field(s)", "{0} 个新字段"),
        ("Doc_CountRemoved", "{0} removed", "{0} 处删除"),
        ("Doc_CountErrors", "{0} error(s)", "{0} 个错误"),
        ("Doc_CountWarnings", "{0} warning(s)", "{0} 个警告"),
        ("Doc_Reordered", "Field order changed", "字段顺序已调整"),
        ("Doc_NewFields", "New document · {0} fields", "新文档 · {0} 个字段"),
        ("Doc_FixToSave", "Fix the errors to save", "修正错误后才能保存"),
        ("Doc_NoChanges", "No changes", "没有修改"),
        ("Doc_ViewReadOnly", "Views can't be edited in place", "视图只读 · 不能原地修改"),
        ("Doc_ReadOnlyMode", "Read-only mode — unlock writes to save", "只读模式 · 解锁写入后才能保存"),
        ("Doc_SaveAsNew", "Save as new", "另存为新文档"),

        // ── 粘贴与补全 ──
        ("Doc_PasteEmpty", "The clipboard has no document", "剪贴板里没有文档"),
        ("Doc_PasteBad", "The clipboard isn't a JSON / EJSON document: {0}", "剪贴板内容不是 JSON / EJSON 文档:{0}"),
        ("Doc_Pasted", "Loaded {0} fields from the clipboard", "已从剪贴板载入 {0} 个字段"),
        ("Doc_PasteKeptId", "Kept this document's _id", "保留了本文档的 _id"),
        ("Doc_SampleFailed", "Couldn't sample the collection: {0}", "抽样失败:{0}"),
        ("Doc_FillNone", "Nothing to fill — this document has every common field", "无需补全 · 本文档已包含所有常见字段"),
        ("Doc_Filled", "Added {0} field(s): {1}", "已补全 {0} 个字段:{1}"),

        // ── 保存 ──
        ("Doc_ConfirmTitle", "Save document", "保存文档"),
        ("Doc_ConfirmBody", "{0} is a production connection. Write to {1} with {2}?", "{0} 是生产连接。确定用 {2} 写入 {1}?"),
        ("Doc_ConfirmCommand", "Command", "命令"),
        ("Doc_ConfirmFields", "Fields", "字段"),
        ("Doc_WholeDocument", "Whole document", "整份文档"),
        ("Doc_Saved", "Saved to {0}", "已保存到 {0}"),
        ("Doc_SavedDetail", "{0} · {1} field(s) · {2} ms", "{0} · {1} 个字段 · {2} ms"),
        ("Doc_Inserted", "Inserted into {0}", "已插入 {0}"),
        ("Doc_Conflict", "Not saved: the document changed on the server", "未保存:文档已在服务器上被修改"),
        ("Doc_ConflictDetail", "updatedAt no longer matches (or the document was deleted). Your edits are still here.",
            "updatedAt 已不匹配(或文档已被删除),没有覆盖。你的修改仍在编辑器里。"),
        ("Doc_ConflictDeleted", "No document matched this _id any more. Your edits are still here.",
            "已没有这个 _id 的文档,没有写入。你的修改仍在编辑器里。"),
        ("Doc_Rebase", "Redo on latest", "基于最新版本重做"),
        ("Doc_Rebased", "Re-applied your edits on the latest version", "已把你的修改重放到最新版本上"),
        ("Doc_Deleted", "The document no longer exists", "文档已不存在"),
        ("Doc_ServerRejected", "The server rejected the document (validation)", "服务器拒绝了该文档(验证规则)"),

        // ── 客户端 $jsonSchema 预检(验证规则页也用)──
        ("Schema_WholeDocument", "document", "文档"),
        ("Schema_MustBeType", "{0} must be {1} (got {2})", "{0} 须为 {1} 类型(当前为 {2})"),
        ("Schema_NotInEnum", "{0} is not in the enum ({1})", "{0} 不在枚举中({1})"),
        ("Schema_MinValue", "{0} must be ≥ {1}", "{0} 须 ≥ {1}"),
        ("Schema_MinValueExclusive", "{0} must be > {1}", "{0} 须 > {1}"),
        ("Schema_MaxValue", "{0} must be ≤ {1}", "{0} 须 ≤ {1}"),
        ("Schema_MaxValueExclusive", "{0} must be < {1}", "{0} 须 < {1}"),
        ("Schema_NotMultipleOf", "{0} must be a multiple of {1}", "{0} 须为 {1} 的倍数"),
        ("Schema_TooShort", "{0} needs at least {1} characters", "{0} 至少 {1} 个字符"),
        ("Schema_TooLong", "{0} allows at most {1} characters", "{0} 最多 {1} 个字符"),
        ("Schema_PatternMismatch", "{0} doesn't match {1}", "{0} 不匹配 {1}"),
        ("Schema_MissingRequired", "Missing required field {0}", "缺少必填字段 {0}"),
        ("Schema_TooFewFields", "{0} needs at least {1} fields", "{0} 至少要有 {1} 个字段"),
        ("Schema_TooManyFields", "{0} allows at most {1} fields", "{0} 最多 {1} 个字段"),
        ("Schema_FieldNotAllowed", "{0} is not allowed (additionalProperties: false)", "不允许的字段 {0}(additionalProperties: false)"),
        ("Schema_TooFewItems", "{0} needs at least {1} items", "{0} 至少 {1} 项"),
        ("Schema_TooManyItems", "{0} allows at most {1} items", "{0} 最多 {1} 项"),
        ("Schema_DuplicateItems", "{0} has duplicate items", "{0} 有重复项"),
        ("Schema_ExtraItems", "{0} allows only {1} items", "{0} 只允许 {1} 项"),
        ("Schema_NoAnyOf", "{0} matches none of anyOf", "{0} 不满足 anyOf 中的任何一项"),
        ("Schema_NotOneOf", "{0} must match exactly one of oneOf (matched {1})", "{0} 须恰好满足 oneOf 中的一项(满足了 {1} 项)"),
        ("Schema_MatchesNot", "{0} must not match the not schema", "{0} 不能满足 not 中的条件"),
    ];
}
