namespace VelaShell.Plugin.Mongo;

public sealed partial class Loc
{
    /// <summary>用户与角色。</summary>
    private static readonly (string Key, string En, string Zh)[] UsersTexts =
    [
        // ── 工具行与列表 ──
        ("Users_NewUser", "New user", "新建用户"),
        ("Users_NewRole", "New role", "新建角色"),
        ("Users_ResetPassword", "Reset password", "重置密码"),
        ("Users_ColUser", "User", "用户"),
        ("Users_ColAuthDb", "Auth DB", "认证库"),
        ("Users_ColRoles", "Roles", "角色"),
        ("Users_ColRole", "Role", "角色"),
        ("Users_ColRoleDb", "Database", "所在库"),
        ("Users_ColInherits", "Inherits", "继承"),
        ("Users_Editing", "Editing", "编辑中"),
        ("Users_RoleRowSummary", "{0} privileges · {1} users", "{0} 条权限 · {1} 个用户"),
        ("Users_NoUsers", "No users", "没有用户"),
        ("Users_NoRoles", "No custom roles", "没有自定义角色"),
        ("Users_ScopedNotice", "No privilege to list the users of every database — showing {0} only.",
            "没有查看全部库用户的权限 —— 只列出 {0} 库的用户"),
        ("Users_LoadFailed", "Loading users failed: {0}", "加载用户失败：{0}"),
        ("Users_EmptyEditor", "Pick a user on the left, or create one.", "在左侧选一个用户,或新建一个"),
        ("Users_EmptyRoleEditor", "Pick a role on the left, or create one.", "在左侧选一个角色,或新建一个"),
        ("Users_Status", "{0} · {1} users · {2} custom roles", "{0} · {1} 个用户 · {2} 个自定义角色"),
        ("Users_StatusPending", "Unsaved: {0}", "未保存：{0}"),
        ("Users_RefreshDiscardTitle", "Discard unsaved changes?", "放弃未保存的修改?"),
        ("Users_RefreshDiscardBody", "Reloading users and roles drops the changes that were not saved.",
            "重新加载用户与角色会丢掉尚未保存的修改。"),

        // ── 用户编辑器 ──
        ("Users_NewUserTitle", "New user", "新用户"),
        ("Users_NotCreated", "not created yet", "尚未创建"),
        ("Users_CreatedOn", "created {0}", "创建于 {0}"),
        ("Users_CurrentIdentity", "this connection", "当前连接身份"),
        ("Users_PasswordAge", "Password unchanged for {0} days · policy {1} days", "密码 {0} 天未修改 · 策略 {1} 天"),
        ("Users_Rotate", "Rotate password", "轮换密码"),
        ("Users_RotateTip", "Generate a strong random password, apply it, copy it and show it once",
            "生成强随机密码并立即生效;复制到剪贴板,只显示一次"),
        ("Users_Account", "Account", "账号"),
        ("Users_UserName", "User name", "用户名"),
        ("Users_AuthDb", "Authentication database", "认证库"),
        ("Users_Password", "Password", "密码"),
        ("Users_Mechanism", "Mechanism", "认证机制"),
        ("Users_Generate", "Generate", "生成"),
        ("Users_GenerateTip", "Strong random password: 24 characters, safe inside a connection string without escaping",
            "强随机密码:24 位,放进连接串无需转义"),
        ("Users_RevealPassword", "Show the password", "显示密码"),
        ("Users_BuiltinRoles", "Built-in roles", "内置角色"),
        ("Users_BuiltinHint", "Tick to grant; changes are marked orange", "勾选即授予；变更以橙色标出"),
        ("Users_ColDatabase", "Database", "数据库"),
        ("Users_AnyDatabase", "All databases (anyDatabase)", "所有数据库 (anyDatabase)"),
        ("Users_CustomRoles", "Custom roles", "自定义角色"),
        ("Users_AddRole", "Add role", "添加角色"),
        ("Users_NoAddable", "Nothing else to add", "没有可添加的角色"),
        ("Users_Restrictions", "Login restrictions authenticationRestrictions", "登录限制 authenticationRestrictions"),
        ("Users_ClientSource", "clientSource", "clientSource"),
        ("Users_ServerAddress", "serverAddress", "serverAddress"),
        ("Users_Unrestricted", "(unrestricted)", "（不限制）"),
        ("Users_MoreRestrictions", "{0} more restriction set(s) on the server are kept as they are.",
            "服务器上另有 {0} 组限制,保存时原样保留"),
        ("Users_Effective", "Effective privileges", "有效权限预览"),
        ("Users_Computing", "Computing…", "计算中…"),
        ("Users_NoPrivileges", "No privileges — it can log in but do nothing.", "没有任何权限 —— 能登录,但什么也做不了"),
        ("Users_PreviewFailed", "Could not expand the roles: {0}", "无法展开角色权限：{0}"),
        ("Users_NoChanges", "No pending changes", "没有待保存的修改"),
        ("Users_CopyCommands", "Copy the commands", "复制命令"),
        ("Users_BadAddress", "Not an IP address or CIDR: {0}", "不是 IP 地址或 CIDR：{0}"),
        ("Users_NeedName", "Enter a user name", "请填写用户名"),
        ("Users_NeedPassword", "Enter or generate a password", "请填写或生成密码"),
        ("Users_NameTaken", "{0} already exists", "{0} 已存在"),

        // ── 角色编辑器 ──
        ("Users_NewRoleTitle", "New role", "新角色"),
        ("Users_RoleSummary", "{0} privileges · held by {1} users", "{0} 条权限 · {1} 个用户持有"),
        ("Users_RoleDefinition", "Role", "角色"),
        ("Users_RoleName", "Role name", "角色名"),
        ("Users_RoleDb", "Database", "所在库"),
        ("Users_InheritedBuiltin", "Inherited built-in roles", "继承的内置角色"),
        ("Users_InheritedOther", "Inherited roles", "继承的其他角色"),
        ("Users_OwnPrivileges", "Privileges", "权限"),
        ("Users_AddPrivilege", "Add privilege", "添加权限"),
        ("Users_NoOwnPrivileges", "No privileges of its own — everything comes from inherited roles.", "没有自有权限 —— 全部来自继承的角色"),
        ("Users_RemovePrivilege", "Remove this privilege", "删除这条权限"),
        ("Users_ResourceDb", "db", "db"),
        ("Users_ResourceCollection", "collection", "collection"),
        ("Users_AllDatabases", "(all databases)", "（所有库）"),
        ("Users_AllCollections", "(all collections)", "（全部集合）"),
        ("Users_HoldersTitle", "Users holding it", "持有该角色的用户"),
        ("Users_NoHolders", "No user holds it directly", "没有用户直接持有它"),
        ("Users_NeedRoleName", "Enter a role name", "请填写角色名"),
        ("Users_AnyDbOnlyAdmin", "An empty database name (all databases) is only allowed for roles in admin",
            "库名留空(所有库)只能用于 admin 库里的角色"),

        // ── 保存 / 删除 / 密码 ──
        ("Users_SaveUserTitle", "Save user {0}", "保存用户 {0}"),
        ("Users_SaveRoleTitle", "Save role {0}", "保存角色 {0}"),
        ("Users_ConfirmCommands", "{0} command(s) will run:", "将执行 {0} 条命令:"),
        ("Users_Saved", "Saved {0}", "已保存 {0}"),
        ("Users_SavedDetail", "{0} command(s) applied", "已执行 {0} 条命令"),
        ("Users_Created", "Created {0}", "已创建 {0}"),
        ("Users_PasswordCopied", "The generated password is on the clipboard.", "生成的密码已复制到剪贴板"),
        ("Users_RevokeSelfTitle", "Revoke roles from yourself?", "撤销自己的角色?"),
        ("Users_RevokeSelfBody",
            "{0} is the identity this connection uses. If a revoked role is what lets it manage users, this connection cannot undo the change.",
            "{0} 是当前连接所用的身份。被撤销的角色如果正是管理用户的那个,这条连接将无法再把它改回来。"),
        ("Users_RevokeSelfConfirm", "Revoke anyway", "仍然撤销"),
        ("Users_CannotDeleteSelf", "{0} is the identity of this connection", "{0} 是当前连接正在使用的身份"),
        ("Users_CannotDeleteSelfDetail", "Deleting it would lock this connection out. Connect as another administrator to delete it.",
            "删掉它,这条连接的下一条命令就会认证失败。请换一个管理员身份连接后再删。"),
        ("Users_DeleteUserTitle", "Delete user", "删除用户"),
        ("Users_DeleteUserBody", "{0} and all of its role grants will be deleted. Applications using it can no longer log in. This cannot be undone.",
            "将删除用户 {0} 及其全部角色授予。用它连接的应用将无法再登录。此操作无法撤销。"),
        ("Users_DeleteRoleTitle", "Delete role", "删除角色"),
        ("Users_DeleteRoleBody", "Role {0} will be deleted; the {1} user(s) holding it lose its privileges immediately. This cannot be undone.",
            "将删除角色 {0},持有它的 {1} 个用户会立即失去它带来的权限。此操作无法撤销。"),
        ("Users_Privileges", "Privileges", "权限"),
        ("Users_Holders", "Held by", "持有者"),
        ("Users_Deleted", "Deleted {0}", "已删除 {0}"),
        ("Users_RotateTitle", "Rotate the password of {0}?", "轮换 {0} 的密码?"),
        ("Users_RotateBody",
            "A strong random password replaces the current one of {0}. It is copied to the clipboard and shown once. Applications still using the old password fail at their next login.",
            "将为 {0} 生成一个强随机密码并立即替换当前密码;新密码复制到剪贴板并只显示一次。仍在用旧密码的应用下次登录时会失败。"),
        ("Users_PasswordChanged", "Password of {0} changed", "已更新 {0} 的密码"),
        ("Users_ResetTitle", "Reset password", "重置密码"),
        ("Users_NewPassword", "New password", "新密码"),
        ("Users_ConfirmPassword", "Type it again", "再输一遍"),
        ("Users_PasswordMismatch", "The two entries differ", "两次输入不一致"),
        ("Users_PasswordWeak", "Shorter than 12 characters — consider generating one", "短于 12 位 —— 建议直接生成"),
        ("Users_ResetHint",
            "The old password stops working at once. Connections that already authenticated stay up and fail only when they authenticate again.",
            "保存后旧密码立即失效。已经认证的连接不受影响,下次重新认证时才会被拒。"),
        ("Users_ResetApply", "Reset password", "重置密码"),
        ("Users_RevealTitle", "New password", "新密码"),
        ("Users_RevealCopied", "Copied to the clipboard", "已复制到剪贴板"),
        ("Users_RevealHint",
            "This is the only time it is shown: the server keeps only a salted hash and VelaShell keeps no copy.",
            "这是唯一一次显示:服务器只保存加盐摘要,VelaShell 也不留底 —— 关掉之后无法再查看。"),
        ("Users_RevealDone", "Done", "完成"),
    ];
}
