namespace VelaShell.Plugin.Mongo;

public sealed partial class Loc
{
    /// <summary>工作台外壳:工具栏、对象树、对象标签、服务器徽章、只读开关、确认框。</summary>
    private static readonly (string Key, string En, string Zh)[] WorkspaceTexts =
    [
        // ── Navicat 工具栏 ──
        ("Toolbar_NewQuery", "New query", "新建查询"),
        ("Toolbar_Aggregate", "Aggregate", "聚合"),
        ("Toolbar_Collections", "Collections", "集合"),
        ("Toolbar_Views", "Views", "视图"),
        ("Toolbar_Indexes", "Indexes", "索引"),
        ("Toolbar_GridFs", "GridFS", "GridFS"),
        ("Toolbar_Users", "Users", "用户"),
        ("Toolbar_Roles", "Roles", "角色"),
        ("Toolbar_Import", "Import", "导入"),
        ("Toolbar_Export", "Export", "导出"),
        ("Toolbar_Dump", "Dump", "转储"),
        ("Toolbar_Transfer", "Transfer", "数据传输"),
        ("Toolbar_Monitor", "Monitor", "服务器监控"),
        ("Toolbar_SlowQueries", "Slow queries", "慢查询"),
        ("Toolbar_ReadWrite", "Read/Write", "读写"),
        ("Toolbar_ReadOnlyOn", "Read-only", "只读模式"),
        ("Toolbar_ReadOnlyTip", "Read-only mode blocks every edit, delete and import on this connection. Turn it off to unlock writes.",
            "只读模式下本连接的编辑、删除、导入一律禁用;关掉它即解锁写入。"),
        ("Toolbar_Unlock", "Unlock writes", "解锁写入"),
        ("Toolbar_UnlockTitle", "Unlock writes on production?", "在生产连接上解锁写入?"),
        ("Toolbar_UnlockBody", "{0} is marked as production. Writes stay unlocked until you turn read-only back on or close the tab.",
            "{0} 标记为生产环境。解锁后写入一直可用,直到你重新打开只读或关闭标签页。"),
        ("Toolbar_PickCollection", "Select a collection in the tree first", "先在对象树里选中一个集合"),

        // ── 导航栏 / 对象树 ──
        ("Nav_Objects", "Objects", "对象"),
        ("Nav_Filter", "Filter objects…", "筛选对象…"),
        ("Nav_NewCollection", "New collection", "新建集合"),
        ("Nav_NewView", "New view", "新建视图"),
        ("Nav_Refresh", "Refresh", "刷新"),
        ("Nav_CollapseAll", "Collapse all", "全部折叠"),
        ("Nav_ShowSystemDbs", "Show system databases (admin / config / local)", "显示系统库(admin / config / local)"),
        ("Nav_HideSystemDbs", "Hide system databases (admin / config / local)", "隐藏系统库(admin / config / local)"),
        ("Tree_Collections", "Collections", "集合"),
        ("Tree_Views", "Views", "视图"),
        ("Tree_Buckets", "GridFS buckets", "GridFS 存储桶"),
        ("Tree_Users", "Users & roles", "用户与角色"),
        ("Tree_Functions", "Stored functions system.js", "存储函数 system.js"),
        ("Tree_FileCount", "{0} files", "{0} 个文件"),
        ("Tag_Ttl", "TTL", "TTL"),
        ("Tag_TimeSeries", "Time series", "时序"),
        ("Tag_Capped", "Capped", "固定"),
        ("Tag_Clustered", "Clustered", "聚簇"),
        ("Tree_Open", "Open", "打开"),
        ("Tree_Design", "Design collection", "设计集合"),
        ("Tree_Pipeline", "Open in pipeline builder", "在管道构建器中打开"),
        ("Tree_NewQuery", "New query", "新建查询"),
        ("Tree_Objects", "Object list", "对象列表"),
        ("Tree_Export", "Export…", "导出…"),
        ("Tree_Import", "Import…", "导入…"),
        ("Tree_CopyName", "Copy name", "复制名称"),
        ("Tree_Empty", "Empty collection…", "清空集合…"),
        ("Tree_Drop", "Drop…", "删除…"),
        ("Tree_DropDb", "Drop database…", "删除数据库…"),
        ("Tree_Refresh", "Refresh", "刷新"),
        ("Tree_Profiler", "Slow queries", "慢查询"),
        ("Tree_NewCollection", "New collection…", "新建集合…"),
        ("Tree_NewView", "New view…", "新建视图…"),
        ("Tree_NewBucket", "New bucket…", "新建存储桶…"),
        ("Tree_UploadFiles", "Upload files…", "上传文件…"),
        ("Tree_UploadFolder", "Upload folder…", "上传文件夹…"),
        ("Tree_DropBucket", "Drop bucket…", "删除存储桶…"),
        ("Tree_EmptyTitle", "Empty collection", "清空集合"),
        ("Tree_EmptyBody", "Delete all {1} documents in {0}? Indexes and validation rules are kept. This cannot be undone.",
            "删除 {0} 中全部 {1} 份文档?索引与验证规则保留。此操作无法撤销。"),
        ("Tree_EmptyConfirm", "Delete all documents", "删除全部文档"),
        ("Tree_EmptyDone", "Deleted {0} documents", "已删除 {0} 份文档"),

        // ── 底部信息区 ──
        ("Detail_Documents", "Documents", "文档"),
        ("Detail_StorageIndex", "Storage / index", "存储 / 索引"),
        ("Detail_Indexes", "Indexes", "索引"),
        ("Detail_IndexSummary", "{0} · avg doc {1}", "{0} · 平均文档 {1}"),
        ("Detail_View", "View", "视图"),
        ("Detail_ViewOn", "Source", "源集合"),
        ("Detail_Stages", "Stages", "阶段"),
        ("Detail_Database", "Database", "数据库"),
        ("Detail_CollectionsViews", "Collections / views", "集合 / 视图"),
        ("Detail_DataIndex", "Data / index", "数据 / 索引"),
        ("Detail_Buckets", "{0} buckets", "{0} 个存储桶"),
        ("Detail_Bucket", "GridFS bucket", "GridFS 存储桶"),
        ("Detail_Files", "Files", "文件"),
        ("Detail_TotalSize", "Total size", "总大小"),
        ("Detail_Chunks", "Chunks", "块 (chunks)"),
        ("Detail_Version", "Version", "版本"),
        ("Detail_Endpoint", "Endpoint", "端点"),
        ("Detail_User", "User", "用户"),
        ("Detail_Anonymous", "(no auth)", "(未认证)"),

        // ── 标签页 ──
        ("Tab_CloseModifiedTitle", "Discard unsaved changes?", "放弃未保存的修改?"),
        ("Tab_CloseModifiedBody", "{0} has unsaved changes. Closing the tab discards them and can't be undone.",
            "{0} 有未保存的修改,关闭标签页将放弃这些更改,且无法恢复。"),
        ("Tab_CloseDiscard", "Discard and close", "放弃并关闭"),
        ("Tab_Close", "Close", "关闭"),
        ("Tab_CloseOthers", "Close others", "关闭其他"),

        // ── 外壳 ──
        ("Workspace_Disconnected", "Connection lost — the driver keeps retrying in the background. Results on screen may be stale.",
            "连接已断开 —— 驱动在后台持续重试,屏幕上的结果可能已过期。"),

        // ── 对话框 ──
        ("Dialog_DiscardTitle", "Discard and close?", "放弃并关闭?"),
        ("Dialog_DiscardBody", "{0} has changes that were not saved, or work still running. Closing now discards it.",
            "「{0}」有未保存的修改或仍在执行的操作,现在关闭会丢掉它们。"),
        ("Dialog_DiscardConfirm", "Discard and close", "放弃并关闭"),

        // ── 确认框 ──
        ("Confirm_TypeName", "Type the name to confirm", "输入名称以确认"),
        ("Confirm_DataSize", "Data size", "数据大小"),
        ("Confirm_LastWrite", "Last write", "最近写入"),
        ("Confirm_DropTitle", "Drop collection", "删除集合"),
        ("Confirm_DropViewTitle", "Drop view", "删除视图"),
        ("Confirm_DropBody", "This permanently deletes {0} and its {1} indexes. This cannot be undone.",
            "将永久删除 {0} 及其 {1} 个索引。此操作无法撤销。"),
        ("Confirm_DropViewBody", "This drops the view {0}. Its source collection is not touched.",
            "将删除视图 {0},其源集合不受影响。"),
        ("Confirm_BackupFirst", "Back up with mongodump first…", "先用 mongodump 备份…"),
        ("Confirm_Dropped", "Dropped {0}", "已删除 {0}"),
        ("Confirm_DropDbTitle", "Drop database", "删除数据库"),
        ("Confirm_DropDbBody", "This permanently deletes the database {0} with every collection, index and user in it.",
            "将永久删除数据库 {0},连同其中所有集合、索引与用户。"),
    ];
}
