namespace VelaShell.Plugin.Mongo;

public sealed partial class Loc
{
    /// <summary>查询编辑器:编辑器、补全、结果页、执行计划。</summary>
    private static readonly (string Key, string En, string Zh)[] QueryTexts =
    [
        // ── 标签与工具行 ──
        ("Query_Title", "Query {0}", "查询 {0}"),
        ("Query_Run", "Run", "运行"),
        ("Query_RunCurrent", "Run statement", "运行当前语句"),
        ("Query_Stop", "Stop", "停止"),
        ("Query_Explain", "Explain", "执行计划"),
        ("Query_Format", "Format", "格式化"),
        ("Query_History", "History", "历史"),
        ("Query_ExportCode", "Export as code", "导出为代码"),
        ("Query_Unlimited", "unlimited", "不限"),
        ("Query_MaxTimeTip", "Default server-side time limit for each statement (a .maxTimeMS() in the statement wins)",
            "每条语句默认的服务器端超时(语句里写了 .maxTimeMS() 以语句为准)"),
        ("Query_DatabaseTip", "Database the statements run on — same as running use; db.<name> resolves here", "语句在哪个库上执行 —— 切换等同于执行 use;db.<集合> 在这个库里解析"),
        ("Query_ConnectionLabel", "Connection", "连接"),
        ("Query_DatabaseLabel", "Database", "数据库"),
        ("Query_ConnectionTip", "Connection the statements run on — switching keeps the script", "语句在哪条连接上执行 —— 切换时脚本原样带过去"),
        ("Query_ConnNotConnected", "not connected", "未连接"),
        ("Query_ConnFailed", "failed", "连接失败"),
        ("Query_SwitchingTo", "Connecting {0}…", "正在连接 {0}…"),
        ("Query_TargetHint", "Runs on {0} / {1}", "在 {0} / {1} 上执行"),
        ("Query_SwitchWhileRunning", "Stop the running statements before switching connections", "先停止正在运行的语句,再切换连接"),
        ("Query_SwitchFailed", "Couldn't connect {0}", "无法连接 {0}"),
        ("Query_SwitchedTo", "The query now runs on {0} · {1}", "查询已切换到 {0} · {1}"),
        ("Query_SwitchedDbMissing", "{0} has no database {1}; using {2}", "{0} 上没有库 {1},改用 {2}"),
        ("Query_CollectionMissing", "No collection {0} in database {1} — check the database picker or use()", "库 {1} 里没有集合 {0} —— 核对上方的数据库或 use()"),

        // ── 状态 ──
        ("Query_StatusUnsaved", "Query {0} · unsaved", "查询 {0} · 未保存"),
        ("Query_StatusSaved", "Saved as “{0}”", "已保存为「{0}」"),
        ("Query_StatusRun", "{0} rows · {1}", "{0} 行 · {1}"),
        ("Query_NothingToRun", "Nothing to run", "没有可运行的语句"),
        ("Query_Running", "Running {0}/{1}…", "正在执行 {0}/{1}…"),
        ("Query_ExecDone", "{0} statements completed", "{0} 条语句执行完成"),
        ("Query_ExecStopped", "Stopped after {0} of {1}", "已停止({0}/{1})"),
        ("Query_ExecFailed", "Statement {0} of {1} failed", "第 {0}/{1} 条语句失败"),
        ("Query_PlanScan", "examined {0} / returned {1}", "扫描 {0} / 返回 {1}"),
        ("Query_Problems", "{0} problem(s)", "{0} 个问题"),
        ("Query_FixHint", "Alt+↵ fix", "Alt+↵ 修复"),

        // ── 结果区 ──
        ("Query_ResultN", "Result {0}", "结果 {0}"),
        ("Query_TabMessages", "Messages", "消息"),
        ("Query_TabExplain", "Explain plan", "执行计划"),
        ("Query_ViewGrid", "Grid", "网格"),
        ("Query_ViewTree", "Tree", "树"),
        ("Query_ViewJson", "JSON", "JSON"),
        ("Query_Export", "Export", "导出"),
        ("Query_Pin", "Pin result", "固定结果"),
        ("Query_PinTip", "A pinned result stays when you run again", "固定的结果不会被下一次运行覆盖"),
        ("Query_ResultEmpty", "No documents", "没有文档"),
        ("Query_TruncatedNotice", "Only the first {0} documents were fetched — change limit to see more", "只取前 {0} 份,改 limit 看更多"),
        ("Query_MessagesEmpty", "No messages yet. F5 runs every statement, Ctrl+↵ the one under the caret.",
            "还没有消息。F5 运行全部语句,Ctrl+↵ 运行光标所在语句。"),
        ("Query_ExportJsonTitle", "Export result as JSON", "把结果导出为 JSON"),
        ("Query_Exported", "Saved {0}", "已保存 {0}"),
        ("Query_MenuCopyValue", "Copy value", "复制值"),
        ("Query_MenuCopyDocument", "Copy document", "复制文档"),
        ("Query_MenuCopyFilter", "Copy as filter", "复制为筛选条件"),

        // ── 消息 ──
        ("Query_MsgUse", "Switched to {0}", "已切换到库 {0}"),
        ("Query_MsgOk", "OK", "完成"),
        ("Query_MsgDocs", "{0} documents", "{0} 份文档"),
        ("Query_MsgTruncated", "First {0} documents (more available)", "只取前 {0} 份(后面还有)"),
        ("Query_MsgNoMatch", "No matching document", "没有匹配的文档"),
        ("Query_MsgInserted", "Inserted {0}", "插入 {0} 份"),
        ("Query_MsgUpdated", "Matched {0}, modified {1}", "匹配 {0},修改 {1}"),
        ("Query_MsgDeleted", "Deleted {0}", "删除 {0} 份"),
        ("Query_MsgBulk", "{0} write operations done", "已执行 {0} 个写操作"),
        ("Query_MsgIndexCreated", "Created index {0}", "已创建索引 {0}"),
        ("Query_MsgIndexDropped", "Dropped index {0}", "已删除索引 {0}"),
        ("Query_MsgDropped", "Dropped collection {0}", "已删除集合 {0}"),
        ("Query_MsgRenamed", "Renamed {0} → {1}", "已重命名 {0} → {1}"),
        ("Query_MsgExplain", "Explain · {0} · {1}", "执行计划 · {0} · {1}"),
        ("Query_MsgBlocked", "Blocked: read-only mode or no write privilege", "已拦截:只读模式或没有写权限"),
        ("Query_MsgDeclined", "Cancelled — nothing was written", "已取消,什么都没写"),
        ("Query_MsgStopped", "Stopped", "已停止"),
        ("Query_MsgKilled", "Killed {0} operation(s) on the server", "已在服务器上终止 {0} 个操作"),
        ("Query_MsgKillFailed", "Could not kill the server operation: {0}", "未能终止服务器上的操作:{0}"),

        // ── 执行错误 ──
        ("Query_ErrNeedsDocument", "{0} needs a document argument", "{0} 需要一个文档参数"),
        ("Query_ErrNeedsName", "{0} needs a name", "{0} 需要一个名字"),
        ("Query_ErrNeedsArray", "{0} needs an array", "{0} 需要一个数组"),
        ("Query_ErrNeedsPipeline", "{0} needs a pipeline array [ … ]", "{0} 需要一个管道数组 [ … ]"),
        ("Query_ErrUnsupportedMethod", "{0}() is not supported in the query editor", "查询编辑器不支持 {0}()"),
        ("Query_ErrDropDatabaseDisabled", "dropDatabase is disabled for this connection", "这条连接禁用了 dropDatabase"),
        ("Query_ErrBulkOperation", "Unrecognized bulkWrite operation: {0}", "认不出的 bulkWrite 操作:{0}"),
        ("Query_ErrExplainUnsupported", "{0} has no query plan", "{0} 没有执行计划"),

        // ── 解析错误 ──
        ("Query_ParseUnexpected", "Unexpected “{0}”", "这里不该出现「{0}」"),
        ("Query_ParseUnsupported", "“{0}” is not supported — start with db., use or show", "不支持「{0}」:语句要以 db.、use 或 show 开头"),
        ("Query_ParseNeedsDatabase", "Which database?", "要写库名"),
        ("Query_ParseShowTarget", "show {0}: use show dbs or show collections", "show {0}:只支持 show dbs / show collections"),
        ("Query_ParseExpectedName", "Expected a name after “.”", "「.」后面要跟名字"),
        ("Query_ParseUnclosed", "Unclosed “{0}”", "「{0}」没有配对"),
        ("Query_ParseNeedsMethod", "{0}: call a method, e.g. .find()", "{0} 后面要调用方法,如 .find()"),
        ("Query_ParseNeedsCollection", "getCollection needs a collection name", "getCollection 要写集合名"),
        ("Query_ParseUnknownDbMethod", "db.{0} is not a database method — collections look like db.{0}.find()",
            "db.{0} 不是库方法;集合要写成 db.{0}.find()"),
        ("Query_ParseNeedsCall", "{0} needs parentheses: {0}(…)", "{0} 要加括号:{0}(…)"),
        ("Query_ParseUnknownCursor", "Unknown cursor method {0}()", "未知的游标方法 {0}()"),
        ("Query_ParseFunction", "Function arguments are not supported in the query editor", "查询编辑器不支持函数实参"),
        ("Query_ParseLiteral", "Syntax error: {0}", "语法错误:{0}"),

        // ── 写前确认 ──
        ("Query_ConfirmNamespace", "Namespace", "命名空间"),
        ("Query_ConfirmFilter", "Filter", "条件"),
        ("Query_ConfirmAffected", "Documents affected", "预计影响"),
        ("Query_ConfirmIndex", "Index", "索引"),
        ("Query_ConfirmDocs", "Documents", "文档"),
        ("Query_ConfirmRun", "Run", "执行"),
        ("Query_ConfirmDelete", "Delete", "删除"),
        ("Query_ConfirmDropLabel", "Drop", "删除"),
        ("Query_ConfirmUpdateManyTitle", "Update many documents", "批量更新"),
        ("Query_ConfirmUpdateManyBody", "updateMany will modify every document in {0} that matches the filter.",
            "updateMany 会修改 {0} 中所有匹配条件的文档。"),
        ("Query_ConfirmDeleteManyTitle", "Delete many documents", "批量删除"),
        ("Query_ConfirmDeleteManyBody", "deleteMany will permanently delete every document in {0} that matches the filter. This cannot be undone.",
            "deleteMany 会永久删除 {0} 中所有匹配条件的文档。此操作无法撤销。"),
        ("Query_ConfirmBulkTitle", "Bulk write", "批量写入"),
        ("Query_ConfirmBulkBody", "bulkWrite will run {1} write operations on {0}, including bulk updates or deletes.",
            "bulkWrite 将在 {0} 上执行 {1} 个写操作,其中含批量更新或删除。"),
        ("Query_ConfirmDropTitle", "Drop collection", "删除集合"),
        ("Query_ConfirmDropBody", "drop() will permanently delete {0} and all of its indexes. This cannot be undone.",
            "drop() 将永久删除 {0} 及其全部索引。此操作无法撤销。"),
        ("Query_ConfirmDropIndexTitle", "Drop index", "删除索引"),
        ("Query_ConfirmDropIndexBody", "Drop index {0} on {1}? Queries that use it fall back to other plans.",
            "删除 {1} 上的索引 {0}?用到它的查询会改走别的计划。"),
        ("Query_ConfirmDropDatabaseTitle", "Drop database", "删除数据库"),
        ("Query_ConfirmDropDatabaseBody", "dropDatabase() will permanently delete database {0} and everything in it.",
            "dropDatabase() 将永久删除库 {0} 及其中的一切。"),

        // ── 执行计划 ──
        ("Query_NothingToExplain", "Put the caret on a find or aggregate statement", "把光标放在 find / aggregate 语句上"),
        ("Query_ExplainWinning", "Winning plan", "获胜计划"),
        ("Query_ExplainVisual", "Visual", "可视化"),
        ("Query_ExplainTree", "Tree", "树"),
        ("Query_ExplainRaw", "Raw JSON", "原始 JSON"),
        ("Query_ExplainEmpty", "Press F6 to explain the statement under the caret", "按 F6 查看光标所在语句的执行计划"),
        ("Query_ExplainBusy", "Running explain…", "正在获取执行计划…"),
        ("Query_ExplainDirection", "Direction", "方向"),
        ("Query_ExplainSortFromIndex", "Sort comes from the index — no in-memory SORT", "排序由索引提供,无内存 SORT"),
        ("Query_ExplainCollScan", "Full collection scan", "全集合扫描"),
        ("Query_ExplainSelectivity", "Selectivity", "选择率"),
        ("Query_ExplainDiscarded", "{0} documents read and then discarded", "{0} 份文档读出后被丢弃"),
        ("Query_ExplainEarlyExit", "Ended early", "提前结束"),
        ("Query_ExplainSortedBytes", "Data sorted", "排序数据量"),
        ("Query_ExplainMemorySort", "Sorted in memory", "在内存中排序"),
        ("Query_ExplainCovered", "Covered query", "覆盖查询"),
        ("Query_ExplainCandidates", "Candidate plans", "候选计划"),
        ("Query_ExplainWinner", "Winner", "获胜"),
        ("Query_ExplainRejected", "Rejected", "拒绝"),
        ("Query_ExplainTrial", "{0} works · returned {1}", "{0} works · 返回 {1}"),
        ("Query_ExplainSingleCandidate", "Only one candidate plan — no trial needed", "只有一个候选计划,无需试运行"),
        ("Query_ExplainTrialNote", "The planner chose after a trial of {0} work units", "查询规划器试运行 {0} 次工作单元后选择"),
        ("Query_ExplainNeedAllPlans", "Switch to allPlansExecution to see trial numbers", "切到 allPlansExecution 查看试运行数据"),
        ("Query_ExplainSummary", "Summary", "摘要"),
        ("Query_ExplainTotal", "Total time", "总耗时"),
        ("Query_ExplainReturned", "Returned", "返回"),
        ("Query_ExplainKeys", "Keys examined", "扫描键"),
        ("Query_ExplainDocs", "Docs examined", "扫描文档"),
        ("Query_ExplainRatio", "Examined / returned", "扫描 / 返回"),
        ("Query_ExplainInMemorySort", "In-memory sort", "内存排序"),
        ("Query_ExplainAdvice", "Suggestions", "优化建议"),
        ("Query_ExplainCreateIndex", "Create this index…", "创建该索引…"),
        ("Query_ExplainHint", "Compare with hint", "用 hint 对比"),
        ("Query_AdviceCollScan", "Full collection scan. Build an index following ESR (equality → sort → range):",
            "全集合扫描(COLLSCAN)。按 ESR(等值 → 排序 → 范围)建立索引:"),
        ("Query_AdviceFetchFilter", "The range filter on {0} runs in the FETCH stage. Following ESR (equality → sort → range), put {0} at the end of the index to filter inside it:",
            "{0} 的范围过滤发生在 FETCH 阶段。按 ESR(等值 → 排序 → 范围)把 {0} 放到索引末尾,可在索引内完成过滤:"),
        ("Query_AdviceSort", "The sort on {0} runs in memory. Following ESR, put the sort fields right after the equality fields:",
            "{0} 的排序在内存中完成。按 ESR 把排序字段紧跟在等值字段之后:"),
        ("Query_AdviceRatio", "It examines {0}× what it returns. An ESR-ordered index narrows the scan:",
            "扫描量是返回量的 {0} 倍。按 ESR 排列的索引能收窄扫描:"),
        ("Query_AdviceNone", "No obvious problem in this plan.", "这个计划没有明显问题。"),
        ("Query_AdvicePredict", "Expected: keys examined ≈ {0}, documents {0}, nothing discarded", "预计:扫描键 ≈ {0},扫描文档 {0},不再有丢弃"),
        ("Query_CreateIndexTitle", "Create index", "创建索引"),
        ("Query_CreateIndexBody", "Create the suggested index on {0}? Building an index on a large collection takes time and server resources.",
            "在 {0} 上创建建议的索引?大集合建索引会占用一段时间与服务器资源。"),
        ("Query_CreateIndexConfirm", "Create index", "创建索引"),
        ("Query_CreateIndexKeys", "Keys", "索引键"),
        ("Query_CreateIndexName", "Name", "名称"),
        ("Query_IndexCreated", "Index {0} created", "已创建索引 {0}"),
        ("Query_OpenIndexes", "View indexes", "查看索引"),
        ("Query_HintTitle", "Compare with hint", "用 hint 对比"),
        ("Query_HintIndex", "Index", "索引"),
        ("Query_HintRun", "Compare", "对比"),
        ("Query_HintCurrent", "Current · {0}", "当前 · {0}"),
        ("Query_HintWith", "hint · {0}", "hint · {0}"),
        ("Query_HintPlan", "Plan", "计划"),

        // ── 补全 ──
        ("Query_CompletionFooter", "↵ insert    Tab insert snippet    Ctrl+Space toggle details", "↵ 插入    Tab 插入片段    Ctrl+Space 切换详情"),
        ("Query_CatKeyword", "keyword", "关键字"),
        ("Query_CatCollection", "collection", "集合"),
        ("Query_CatView", "view", "视图"),
        ("Query_CatDbMethod", "db method", "库方法"),
        ("Query_CatDatabase", "database", "库"),
        ("Query_CatIndex", "index", "索引"),
        ("Query_CatOption", "option", "选项"),
        ("Query_CatSnippet", "snippet", "代码片段"),
        ("Query_CatGroupKey", "group key", "分组键"),
        ("Query_KwDb", "The current database", "当前库"),
        ("Query_KwUse", "Switch the current database", "切换当前库"),
        ("Query_KwShowDbs", "List databases", "列出所有库"),
        ("Query_KwShowCollections", "List the collections of the current database", "列出当前库的集合"),
        ("Query_DbGetCollection", "A collection by name (for names that are not identifiers).", "按名字取集合(名字不是合法标识符时用它)。"),
        ("Query_DbGetCollectionNames", "Names of the collections in this database.", "本库所有集合的名字。"),
        ("Query_DbGetSiblingDb", "Another database on the same server.", "同一台服务器上的另一个库。"),
        ("Query_DbRunCommand", "Runs a database command.", "执行一条数据库命令。"),
        ("Query_DbAdminCommand", "Runs a command against the admin database.", "在 admin 库上执行一条命令。"),
        ("Query_DbStats", "Database statistics.", "库统计。"),
        ("Query_DbCreateCollection", "Creates a collection.", "创建集合。"),
        ("Query_DbAggregate", "Database-level aggregation ($currentOp, $documents…).", "库级聚合($currentOp、$documents…)。"),
        ("Query_FieldSampled", "field · sampled", "字段 · 抽样"),
        ("Query_FieldInfo", "{0} · present in {1} of the sample", "{0} · 出现率 {1}"),
        ("Query_FieldSampleOf", "Sampled from {0} ({1} documents)", "抽样自 {0}({1} 份文档)"),
        ("Query_UpstreamFields", "Fields output by the upstream {0}", "上游 {0} 输出的字段"),
        ("Query_UpstreamField", "upstream field", "上游字段"),
        ("Query_UpstreamFieldHint", "Output of the upstream {0} stage", "上游 {0} 阶段的输出字段"),
        ("Query_GroupIdHint", "Group by this expression; null puts everything in one group.", "按这个表达式分组;null 表示全部归为一组。"),
        ("Query_ValDesc", "descending", "降序"),
        ("Query_ValAsc", "ascending", "升序"),
        ("Query_ValInclude", "include", "保留"),
        ("Query_ValExclude", "exclude", "排除"),
        ("Query_ValRange", "Range comparison.", "范围比较。"),
        ("Query_ValIn", "Matches any of the values.", "匹配其中任一个值。"),
        ("Query_ValExists", "The field is present.", "字段存在。"),
        ("Query_ValRegex", "Regular expression match.", "正则匹配。"),
        ("Query_SnipSortDesc", "$sort descending…", "$sort 降序…"),
        ("Query_SnipSortDescHint", "Sort by a field, largest first.", "按某个字段从大到小排序。"),
        ("Query_SnipMatchEq", "$match equals…", "$match 等值…"),
        ("Query_SnipMatchEqHint", "Keep documents whose field equals a value.", "保留字段等于某个值的文档。"),
        ("Query_SnipGroupCount", "$group count…", "$group 计数…"),
        ("Query_SnipGroupCountHint", "Count documents per value of a field.", "按字段取值分组计数。"),

        // ── 右侧面板 ──
        ("Query_HelperFields", "Fields", "字段"),
        ("Query_HelperSnippets", "Snippets", "片段"),
        ("Query_HelperHistory", "History", "历史"),
        ("Query_HelperHint", "Double-click to insert the field path · or drag it into the editor", "双击插入字段路径 · 拖入编辑器"),
        ("Query_HelperEmpty", "Put the caret on a statement to see the sampled fields of its collection.", "光标放在一条语句上,这里列出它所查集合的抽样字段。"),
        ("Query_HistoryEmpty", "No history yet.", "还没有历史。"),
        ("Query_SampledCount", "sampled {0}", "抽样 {0}"),

        // ── code lens ──
        ("Query_LensRun", "Run", "运行"),
        ("Query_LensExplain", "Explain", "执行计划"),
        ("Query_LensPipeline", "Open in pipeline builder", "在管道构建器中打开"),
        ("Query_LensCopyCs", "Copy as C#", "复制为 C#"),
        ("Query_LensLast", "Last {0} · {1} docs", "上次 {0} · {1} 条"),
        ("Query_LensLastPlain", "Last {0}", "上次 {0}"),
        ("Query_LensFailed", "Last run failed · {0}", "上次失败 · {0}"),

        // ── 保存 / 导出为代码 ──
        ("Query_SaveTitle", "Save query", "保存查询"),
        ("Query_SaveName", "Name", "名称"),
        ("Query_SaveHint", "Saved queries show up under Snippets on the right; saving again under the same name overwrites.",
            "保存后出现在右侧「片段」页;同名再次保存会覆盖。"),
        ("Query_Saved", "Saved “{0}”", "已保存「{0}」"),
        ("Query_NothingToExport", "Nothing to export", "没有可导出的语句"),
        ("Query_ExportCodeTitle", "Export as code", "导出为代码"),
        ("Query_ExportCodeHint", "Literals keep their BSON types", "字面量保留 BSON 类型"),
        ("Query_CodeCopied", "{0} code copied", "已复制 {0} 代码")
    ];
}
