namespace VelaShell.Plugin.Mongo;

public sealed partial class Loc
{
    /// <summary>导出、导入与数据传输向导。</summary>
    private static readonly (string Key, string En, string Zh)[] TransferTexts =
    [
        // ── 三个向导共用 ──
        ("Xfer_DelimComma", ", comma", ", 逗号"),
        ("Xfer_DelimSemicolon", "; semicolon", "; 分号"),
        ("Xfer_DelimTab", "Tab", "Tab 制表符"),
        ("Xfer_DelimPipe", "| pipe", "| 竖线"),
        ("Xfer_LogValidatorKept", "{0}: kept the target's validation rules (append)", "{0}:保留目标已有的验证规则(追加)"),
        ("Xfer_LogIndexFailed", "{0}: indexes not created — {1}", "{0}:索引未建 —— {1}"),
        ("Xfer_View", "View", "查看"),
        ("Xfer_Backgrounded", "Running in the background — you'll be notified when it finishes", "已转入后台,完成后会提示"),
        ("Xfer_Background", "Run in background", "转入后台"),
        ("Xfer_Running", "Running…", "进行中…"),
        ("Xfer_RunningPercent", "Running {0}", "进行中 {0}"),
        ("Xfer_Completed", "Completed", "已完成"),
        ("Xfer_Cancelled", "Cancelled", "已取消"),
        ("Xfer_Failed", "Failed", "失败"),
        ("Xfer_Rate", "{0} docs/s", "{0} 文档/s"),
        ("Xfer_Log", "Log", "日志"),

        // ── 导出(设计稿 19) ──
        ("Exp_StepSource", "Data source", "数据来源"),
        ("Exp_StepFormat", "Format & fields", "格式与字段"),
        ("Exp_StepTarget", "Target & options", "目标与选项"),
        ("Exp_StepRun", "Run", "执行"),
        ("Exp_SummarySingle", "{0} · {1}", "{0} · {1}"),
        ("Exp_SummaryMulti", "{0} · {1} collections", "{0} · {1} 个集合"),
        ("Exp_CurrentFilter", "Current filter", "当前筛选"),
        ("Exp_AllDocuments", "All documents", "全部文档"),
        ("Exp_LocalFile", "Local file", "本地文件"),
        ("Exp_AboutDocs", "About {0} documents", "约 {0} 份文档"),
        ("Exp_LoadProfile", "Load a saved profile", "从保存的配置载入"),
        ("Exp_PickProfile", "Choose a profile…", "选择配置…"),
        ("Exp_Condition", "Condition", "条件"),
        ("Exp_ConditionHint", "mongosh syntax. The sort of the current grid is kept; paging (skip / limit) is not.",
            "mongosh 写法。保留当前网格的排序,不带分页(skip / limit)。"),
        ("Exp_BadFilter", "The filter is not a valid document", "筛选条件不是合法的文档"),
        ("Exp_Collections", "Collections", "集合"),
        ("Exp_SelectAll", "Select all", "全选"),
        ("Exp_SelectNone", "Select none", "全不选"),
        ("Exp_ColCollection", "Collection", "集合"),
        ("Exp_ColDocs", "Documents", "文档数"),
        ("Exp_NoSource", "Select at least one collection", "至少选择一个集合"),
        ("Exp_Format", "Format", "格式"),
        ("Exp_FmtJsonSub", "EJSON · line-delimited", "EJSON · 行分隔"),
        ("Exp_FmtCsvSub", "Flattens nested fields", "扁平化嵌套字段"),
        ("Exp_FmtExcelSub", "xlsx worksheet", "xlsx 工作表"),
        ("Exp_FmtDump", "BSON dump", "BSON 转储"),
        ("Exp_FmtDumpSub", "mongodump compatible", "mongodump 兼容"),
        ("Exp_FmtShell", "Shell script", "Shell 脚本"),
        ("Exp_FmtShellSub", "insertMany statements", "insertMany 语句"),
        ("Exp_Fields", "Fields", "字段"),
        ("Exp_FieldsHint", "From a schema sample · drag to reorder columns", "来自 Schema 抽样 · 拖动调整列顺序"),
        ("Exp_FieldsHintProjection", "From a schema sample · unchecked fields are left out", "来自 Schema 抽样 · 未勾选的字段不导出"),
        ("Exp_FieldsCount", "{0} fields", "{0} 个字段"),
        ("Exp_CollectionsCount", "{0} collections", "{0} 个集合"),
        ("Exp_DocsShort", "{0} docs", "{0} 份"),
        ("Exp_ColPath", "Field path", "字段路径"),
        ("Exp_ColType", "Type", "类型"),
        ("Exp_ColCsvName", "CSV column", "CSV 列名"),
        ("Exp_ColExcelName", "Excel column", "Excel 列名"),
        ("Exp_ColConvert", "Conversion", "转换"),
        ("Exp_ConvHex", "Hex string", "十六进制字符串"),
        ("Exp_ConvFixed2", "2 decimal places", "保留 2 位小数"),
        ("Exp_ConvLocal", "Local time {0}", "本地时间 {0}"),
        ("Exp_ConvIso", "ISO 8601 (UTC)", "ISO 8601(UTC)"),
        ("Exp_ConvJson", "JSON string", "JSON 字符串"),
        ("Exp_ConvNone", "As is", "原样"),
        ("Exp_NullToEmpty", "null → empty", "null → 空"),
        ("Exp_NullToNull", "null → null", "null → null"),
        ("Exp_NoFields", "Select at least one field", "至少勾选一个字段"),
        ("Exp_DumpNotice", "A BSON dump writes whole documents plus each collection's indexes and options, in the same layout as mongodump. Restore it with mongorestore.",
            "BSON 转储导出完整文档,并带上每个集合的索引与选项,目录布局与 mongodump 一致,可直接用 mongorestore 恢复。"),
        ("Exp_MultiNotice", "Several collections: each one gets its own columns from a schema sample at export time.",
            "多个集合:导出时为每个集合各自抽样,自动生成列。"),
        ("Exp_OptCsv", "CSV options", "CSV 选项"),
        ("Exp_OptJson", "JSON options", "JSON 选项"),
        ("Exp_OptExcel", "Excel options", "Excel 选项"),
        ("Exp_OptDump", "Dump options", "转储选项"),
        ("Exp_OptShell", "Script options", "脚本选项"),
        ("Exp_Delimiter", "Delimiter", "分隔符"),
        ("Exp_Encoding", "Encoding", "编码"),
        ("Exp_EncUtf8Bom", "UTF-8 with BOM (Excel friendly)", "UTF-8 带 BOM(Excel 友好)"),
        ("Exp_Nested", "Nested", "嵌套对象"),
        ("Exp_NestedFlatten", "Expand into a.b columns", "展开为 a.b 列"),
        ("Exp_NestedJson", "JSON string", "JSON 字符串"),
        ("Exp_NullValue", "Nulls", "空值"),
        ("Exp_NullEmpty", "Leave empty", "留空"),
        ("Exp_NullLiteral", "Write null", "写 null"),
        ("Exp_WriteHeader", "Write column names in the first row", "首行写入列名"),
        ("Exp_JsonLayout", "Layout", "排列"),
        ("Exp_JsonLines", "One per line", "行分隔"),
        ("Exp_JsonArray", "Array", "数组"),
        ("Exp_JsonMode", "Syntax", "写法"),
        ("Exp_JsonHint", "Relaxed / Canonical are what mongoimport reads; Shell is mongosh literal syntax.",
            "Relaxed / Canonical 可被 mongoimport 读回;Shell 是 mongosh 的字面量写法。"),
        ("Exp_SheetName", "Sheet", "工作表"),
        ("Exp_FreezeHeader", "Freeze the first row", "冻结首行"),
        ("Exp_Gzip", "gzip compress (.bson.gz)", "gzip 压缩(.bson.gz)"),
        ("Exp_DumpHint", "Restore with mongorestore --gzip --dir <folder>.", "用 mongorestore --gzip --dir <目录> 恢复。"),
        ("Exp_ShellBatch", "Per batch", "每条语句"),
        ("Exp_ShellHint", "Documents per insertMany statement. Run the file with mongosh <file>.",
            "每条 insertMany 带的文档数。用 mongosh <文件> 执行。"),
        ("Exp_Preview", "Output preview", "输出预览"),
        ("Exp_Estimate", "Estimate", "预估"),
        ("Exp_EstDocs", "Documents", "文档"),
        ("Exp_EstSize", "File size", "文件大小"),
        ("Exp_EstTime", "Time", "耗时"),
        ("Exp_TargetFile", "Save to file", "保存到文件"),
        ("Exp_TargetFolder", "Save to folder", "保存到目录"),
        ("Exp_TargetPlaceholder", "Choose where to save…", "选择保存位置…"),
        ("Exp_Browse", "Browse…", "浏览…"),
        ("Exp_PickFile", "Export to", "导出到"),
        ("Exp_PickFolder", "Export to folder", "导出到目录"),
        ("Exp_TargetExists", "The target already exists and will be overwritten.", "目标已存在,导出时将覆盖。"),
        ("Exp_Plan", "Plan", "计划"),
        ("Exp_PlanHint", "Documents are streamed from a cursor and written one by one; the file appears only when the export completes.",
            "文档从游标流式读出、逐份写入;导出完成时文件才落定,中途取消不会留下半截文件。"),
        ("Exp_AfterRun", "When finished", "完成后"),
        ("Exp_RevealWhenDone", "Show in file manager", "在资源管理器中显示"),
        ("Exp_Start", "Export · {0} documents", "开始导出 · {0} 份文档"),
        ("Exp_StartPlain", "Export", "开始导出"),
        ("Exp_OverwriteTitle", "Overwrite existing file?", "覆盖已存在的文件?"),
        ("Exp_OverwriteBody", "{0} already exists. The export will replace it.", "{0} 已存在,导出将覆盖它。"),
        ("Exp_Overwrite", "Overwrite", "覆盖"),
        ("Exp_Progress", "Progress", "导出进度"),
        ("Exp_ProgressLine", "{0} / {1} documents · elapsed {2} · remaining {3}", "{0} / {1} 文档 · 已用 {2} · 预计剩余 {3}"),
        ("Exp_ProgressDone", "{0} documents · {1}", "{0} 份文档 · 用时 {1}"),
        ("Exp_LogStart", "Exporting {0} as {1} → {2}", "导出 {0} 为 {1} → {2}"),
        ("Exp_Done", "Exported {0} documents ({1}, {2})", "已导出 {0} 份文档({1},用时 {2})"),
        ("Exp_ToastDone", "Exported {0} documents", "已导出 {0} 份文档"),
        ("Exp_Cancelled", "Export cancelled — no partial file was left behind", "导出已取消,没有留下半截文件"),
        ("Exp_Files", "Files", "文件"),
        ("Exp_Reveal", "Show in file manager", "在资源管理器中显示"),
        ("Exp_CopyPath", "Copy path", "复制路径"),
        ("Exp_Stop", "Stop export", "停止导出"),
        ("Exp_SaveProfile", "Save as export profile", "保存为导出配置"),
        ("Exp_ProfileSaved", "Saved profile “{0}”", "已保存配置「{0}」"),

        // ── 导入(设计稿 20) ──
        ("Imp_StepFile", "Choose file", "选择文件"),
        ("Imp_StepMapping", "Field mapping", "字段映射"),
        ("Imp_StepPreview", "Preview & validate", "预览与校验"),
        ("Imp_StepRun", "Import", "导入"),
        ("Imp_NoFile", "No file chosen", "未选择文件"),
        ("Imp_LoadProfile", "Load a saved profile", "从保存的配置载入"),
        ("Imp_File", "File", "文件"),
        ("Imp_FilePlaceholder", "Choose a CSV, JSON / JSONL or .bson file…", "选择 CSV、JSON / JSONL 或 .bson 文件…"),
        ("Imp_FileHint", "CSV delimiter and encoding (UTF-8 / GBK) are detected automatically; JSON may be an array, one document per line, or mongoexport output.",
            "CSV 自动识别分隔符与编码(UTF-8 / GBK);JSON 可以是数组、一行一份文档或 mongoexport 的输出。"),
        ("Imp_FileMissing", "File not found", "文件不存在"),
        ("Imp_PickFile", "Import from", "从文件导入"),
        ("Imp_KindAll", "Importable files", "可导入的文件"),
        ("Imp_Auto", "Auto", "自动"),
        ("Imp_HasHeader", "First row holds column names", "首行是列名"),
        ("Imp_RawPreview", "First lines", "文件开头"),
        ("Imp_Separated", "{0}-separated", "{0}分隔"),
        ("Imp_Rows", "{0} rows", "{0} 行"),
        ("Imp_Counting", "counting rows…", "正在计数…"),
        ("Imp_KindKeep", "Keep as is", "保持原值"),
        ("Imp_ColSource", "Source column", "源列"),
        ("Imp_ColSample", "Sample", "样例"),
        ("Imp_ColTarget", "Target field", "目标字段"),
        ("Imp_ColType", "Target type", "目标类型"),
        ("Imp_Required", "required", "必填"),
        ("Imp_Unique", "unique", "唯一"),
        ("Imp_RulesText", "Validation rules on the target — required: {0}; enums: {1}", "目标集合有验证规则 —— 必填:{0};枚举:{1}"),
        ("Imp_MappingSummary", "{0} columns → {1} fields", "{0} 列 → {1} 字段"),
        ("Imp_NoMapping", "Map at least one column", "至少映射一列"),
        ("Imp_DuplicateTarget", "Two columns map to the same target field", "有两列映射到了同一个目标字段"),
        ("Imp_TargetTitle", "Target collection", "目标集合"),
        ("Imp_TargetHint", "Default target types come from the collection's validator, then from a sample of its documents, then from the source data.",
            "目标类型默认取集合验证规则声明的类型,其次取集合抽样的主类型,最后按源数据推断。"),
        ("Imp_DryRunSummary", "dry-run {0} rows", "dry-run {0} 行"),
        ("Imp_DryRunning", "Running the dry-run…", "正在 dry-run…"),
        ("Imp_ChipOk", "Importable", "可导入"),
        ("Imp_ChipWarn", "Warnings", "警告"),
        ("Imp_ChipErr", "Errors", "错误"),
        ("Imp_ColLine", "Row", "行"),
        ("Imp_Empty", "(empty)", "(空)"),
        ("Imp_Issues", "Issues", "问题"),
        ("Imp_NoIssues", "No issues found", "没有发现问题"),
        ("Imp_IssueRows", "{0} rows", "{0} 行"),
        ("Imp_DetailFormat", "format {0}", "格式 {0}"),
        ("Imp_DetailGrouping", "thousands separators removed", "去除千分位"),
        ("Imp_DetailSymbols", "quotes and symbols removed", "去除引号与符号"),
        ("Imp_DetailFromString", "source value was a string", "源数据是字符串"),
        ("Imp_DetailFirst", "e.g. row {0}", "如 第 {0} 行"),
        ("Imp_DateFix", "Set date format {0}…", "指定日期格式 {0}…"),
        ("Imp_Recalc", "Recalculate", "重算"),
        ("Imp_WriteMode", "Write mode", "写入方式"),
        ("Imp_ModeInsert", "Insert", "插入"),
        ("Imp_ModeUpsert", "Upsert by key", "按键 upsert"),
        ("Imp_ModeReplace", "Replace", "替换"),
        ("Imp_MatchKey", "Match key", "匹配键"),
        ("Imp_UniqueIndex", "unique index ✓", "唯一索引 ✓"),
        ("Imp_NoUniqueIndex", "no unique index", "无唯一索引"),
        ("Imp_NoKey", "Choose a match key", "请选择匹配键"),
        ("Imp_OnError", "On error", "出错时"),
        ("Imp_OnErrorSkip", "Skip the row and log it to the error report", "跳过该行并写入错误报告"),
        ("Imp_OnErrorStop", "Stop the import", "停止导入"),
        ("Imp_Batch", "Batch size {0} · ordered: false", "批大小 {0} · ordered: false"),
        ("Imp_Backup", "Back up documents that will be overwritten", "导入前备份将被覆盖的文档"),
        ("Imp_Estimate", "Expected result", "预计结果"),
        ("Imp_EstInsert", "Inserted", "新增"),
        ("Imp_EstUpdate", "Updated (upsert hits)", "更新(upsert 命中)"),
        ("Imp_EstSkip", "Skipped (errors)", "跳过(错误)"),
        ("Imp_Start", "Import · {0} rows", "开始导入 · {0} 行"),
        ("Imp_StartPlain", "Import", "开始导入"),
        ("Imp_ConfirmTitle", "Import into this collection?", "导入到这个集合?"),
        ("Imp_ConfirmBody", "Rows from the file will be written to {0} ({1}). Existing documents may change.",
            "文件中的行将写入 {0}({1}),已有文档可能被改动。"),
        ("Imp_FactFile", "File", "文件"),
        ("Imp_FactRows", "Rows", "行数"),
        ("Imp_FactMode", "Write mode", "写入方式"),
        ("Imp_Progress", "Progress", "导入进度"),
        ("Imp_ProgressLine", "{0} / {1} rows · elapsed {2} · remaining {3}", "{0} / {1} 行 · 已用 {2} · 预计剩余 {3}"),
        ("Imp_Rate", "{0} rows/s", "{0} 行/s"),
        ("Imp_LogStart", "Importing {0} → {1} ({2})", "导入 {0} → {1}({2})"),
        ("Imp_Done", "Inserted {0} · updated {1} · skipped {2} · {3}", "新增 {0} · 更新 {1} · 跳过 {2} · 用时 {3}"),
        ("Imp_DoneStopped", "Stopped at the first error — inserted {0} · updated {1} · skipped {2} · {3}",
            "遇到错误已停止 —— 新增 {0} · 更新 {1} · 跳过 {2} · 用时 {3}"),
        ("Imp_Cancelled", "Import stopped — {0} inserted and {1} updated before stopping", "导入已停止 —— 停止前已新增 {0}、更新 {1}"),
        ("Imp_LogReport", "Error report: {0}", "错误报告:{0}"),
        ("Imp_LogBackup", "Backup of overwritten documents: {0}", "覆盖前备份:{0}"),
        ("Imp_ToastDone", "Imported {0} documents", "已导入 {0} 份文档"),
        ("Imp_ToastDetail", "{0} inserted · {1} updated · {2} skipped", "新增 {0} · 更新 {1} · 跳过 {2}"),
        ("Imp_ErrorReport", "Error report", "错误报告"),
        ("Imp_OpenReport", "Show error report", "打开错误报告"),
        ("Imp_NotWritten", "Not written: the ordered batch stopped at row {0}", "未写入:ordered 批次在第 {0} 行出错后停止"),
        ("Imp_Stop", "Stop import", "停止导入"),
        ("Imp_SaveProfile", "Save as import profile", "保存为导入配置"),

        // ── 数据传输(设计稿 21) ──
        ("Xfer_StepEndpoints", "Source & target", "源与目标"),
        ("Xfer_StepObjects", "Objects", "选择对象"),
        ("Xfer_StepOptions", "Options", "选项"),
        ("Xfer_StepRun", "Run", "执行"),
        ("Xfer_Source", "Source", "源"),
        ("Xfer_Target", "Target", "目标"),
        ("Xfer_NoTarget", "No target yet", "尚未选择目标"),
        ("Xfer_PickTarget", "Pick an open session or enter a connection string", "选择已打开的会话,或填写连接串"),
        ("Xfer_Standalone", "standalone", "单节点"),
        ("Xfer_OpenSessions", "Open MongoDB sessions", "已打开的 MongoDB 会话"),
        ("Xfer_NoSessions", "No other MongoDB session is open. Open the target connection in VelaShell first, or enter a connection string below.",
            "没有其他已打开的 MongoDB 会话。先在宿主里打开目标连接,或在下面填写连接串。"),
        ("Xfer_OrUri", "Or connect with a connection string", "或用连接串连接"),
        ("Xfer_Connect", "Connect", "连接"),
        ("Xfer_TargetDatabase", "Target database", "目标库"),
        ("Xfer_NeedTarget", "Choose a target first", "请先选择目标"),
        ("Xfer_BadDatabase", "Not a valid database name", "不是合法的库名"),
        ("Xfer_SameTarget", "Source and target are the same database", "源与目标是同一个库"),
        ("Xfer_Objects", "Collections and GridFS buckets", "集合与 GridFS 存储桶"),
        ("Xfer_ColObject", "Object", "对象"),
        ("Xfer_ColAction", "Target action", "目标动作"),
        ("Xfer_ColCount", "Documents", "文档"),
        ("Xfer_ColProgress", "Progress", "进度"),
        ("Xfer_ColState", "Status", "状态"),
        ("Xfer_ActOverwrite", "Overwrite", "覆盖"),
        ("Xfer_ActAppend", "Append", "追加"),
        ("Xfer_ActCreate", "Create", "新建"),
        ("Xfer_ActSkip", "Skip", "跳过"),
        ("Xfer_ExistsOnTarget", "A collection with this name exists on the target", "目标已存在同名集合"),
        ("Xfer_BucketCount", "{0} files · {1}", "{0} 个文件 · {1}"),
        ("Xfer_ViewDefinition", "view definition", "视图定义"),
        ("Xfer_NothingToDo", "Nothing to transfer — every object is skipped", "没有要传的对象(全部跳过了)"),
        ("Xfer_ObjectsSummary", "{0} collections", "{0} 个集合"),
        ("Xfer_ObjectsSummaryBuckets", "{0} collections · {1} buckets", "{0} 个集合 · {1} 个存储桶"),
        ("Xfer_Options", "Options", "选项"),
        ("Xfer_OptKeepId", "Keep _id", "保留 _id"),
        ("Xfer_OptKeepIdHint", "Off: the target generates new ids (avoids duplicate keys when appending).", "关闭时由目标重新生成 _id(追加到已有集合时避免撞键)。"),
        ("Xfer_OptIndexes", "Transfer indexes", "传输索引"),
        ("Xfer_OptIndexesHint", "Built on the target after the data is written.", "数据写完后在目标上构建。"),
        ("Xfer_OptValidation", "Transfer validation rules", "传输验证规则"),
        ("Xfer_OptValidationHint", "Applied when the collection is created on the target.", "在目标上建集合时带上 validator。"),
        ("Xfer_OptBatch", "Batch size", "批大小"),
        ("Xfer_OptConcurrency", "Parallel", "并发"),
        ("Xfer_OptReadPref", "Source read preference", "源端读偏好"),
        ("Xfer_OptReadPrefHint", "secondaryPreferred keeps the copy off the primary when a secondary is available.",
            "secondaryPreferred:有从节点时从从节点读,不占用主节点。"),
        ("Xfer_IndexesYes", "Yes (built on target)", "是(目标后台构建)"),
        ("Xfer_KeepIdShort", "keep _id", "保留 _id"),
        ("Xfer_IndexesShort", "with indexes", "含索引"),
        ("Xfer_BatchText", "{0} · parallel {1}", "{0} · 并发 {1}"),
        ("Xfer_Start", "Transfer · {0} documents", "开始传输 · {0} 文档"),
        ("Xfer_StartPlain", "Transfer", "开始传输"),
        ("Xfer_ConfirmProdTitle", "Write to a production target?", "写入生产环境的目标?"),
        ("Xfer_ConfirmProdBody", "Data will be written to {0}. Overwritten collections: {1}", "数据将写入 {0}。将被覆盖的集合:{1}"),
        ("Xfer_ConfirmOverwriteTitle", "Overwrite collections on the target?", "覆盖目标上的集合?"),
        ("Xfer_ConfirmOverwriteBody", "These collections on {0} will be dropped and recreated: {1}", "{0} 上的这些集合将被删除并重建:{1}"),
        ("Xfer_FactTarget", "Target", "目标"),
        ("Xfer_FactObjects", "Objects", "对象"),
        ("Xfer_FactDocs", "Documents", "文档"),
        ("Xfer_Overall", "Overall", "总进度"),
        ("Xfer_OverallLine", "{0} / {1} documents · elapsed {2} · remaining {3}", "{0} / {1} 文档 · 已用 {2} · 预计剩余 {3}"),
        ("Xfer_StateQueued", "Queued", "排队"),
        ("Xfer_StateRunning", "Copying", "传输中"),
        ("Xfer_StateDone", "Done", "完成"),
        ("Xfer_StateSkipped", "Skipped", "已跳过"),
        ("Xfer_StateFailed", "Failed", "失败"),
        ("Xfer_StateStopped", "Stopped", "已停止"),
        ("Xfer_LogEmpty", "The log appears here once the transfer starts.", "开始传输后在这里显示日志。"),
        ("Xfer_LogSource", "Source {0} ({1}, {2})", "连接源 {0}({1},{2})"),
        ("Xfer_LogTarget", "Target {0} / {1}", "连接目标 {0} / {1}"),
        ("Xfer_LogOverwrite", "{0} → overwrite: drop + create", "{0} → 覆盖:drop + create"),
        ("Xfer_LogBegin", "{0} started · {1}", "{0} 开始 · {1}"),
        ("Xfer_LogDone", "{0} ✓ · {1} indexes", "{0} ✓ · {1} 个索引"),
        ("Xfer_LogViewDone", "view ✓", "视图 ✓"),
        ("Xfer_LogAppendSuffix", " (append)", "(追加)"),
        ("Xfer_LogFailedDocs", "{0}: {1} documents rejected (duplicate keys etc.)", "{0}:{1} 份文档被拒(重复键等)"),
        ("Xfer_LogSkipped", "{0} skipped", "{0} 已跳过"),
        ("Xfer_LogSkippedExists", "{0} skipped: a collection with this name exists on the target", "{0} 已跳过:目标存在同名集合"),
        ("Xfer_LogStopped", "{0} stopped at {1}", "{0} 在 {1} 处停止"),
        ("Xfer_LogPaused", "Paused (in-flight batches finish first)", "已暂停(在途的批写完为止)"),
        ("Xfer_LogResumed", "Resumed", "已继续"),
        ("Xfer_ResultDone", "Transferred {0} objects · {1} documents · {2}", "已传输 {0} 个对象 · {1} 份文档 · 用时 {2}"),
        ("Xfer_ResultStopped", "Stopped — {0} objects finished, {1} documents copied", "已停止 —— 完成 {0} 个对象,复制 {1} 份文档"),
        ("Xfer_ResultFailed", "{0} objects transferred, {1} failed — see the log", "完成 {0} 个对象,{1} 个失败 —— 见日志"),
        ("Xfer_Pause", "Pause", "暂停"),
        ("Xfer_Resume", "Resume", "继续"),
        ("Xfer_Stop", "Stop transfer", "停止传输"),
        ("Xfer_StopTitle", "Stop the transfer?", "停止传输?"),
        ("Xfer_StopBody", "The current object stops after its in-flight batches; the remaining objects are not started. What was copied stays on the target.",
            "当前对象在在途的批写完后停下,其余对象不再开始。已复制的数据保留在目标上。"),
        ("Xfer_BackgroundLong", "Run in background (notifies when done)", "转入后台(完成后提示)"),

        // ── 导入:问题 ──
        ("Imp_IssueMissing", "Missing required field {0}", "缺少必填字段 {0}"),
        ("Imp_IssueBadDate", "Unparseable date", "日期无法解析"),
        ("Imp_IssueBadNumber", "{0} is not a number", "{0} 无法解析为数值"),
        ("Imp_IssueBadValue", "{0} could not be converted", "{0} 类型无法转换"),
        ("Imp_IssueNumberText", "Text converted to {0}", "字符串自动转为 {0}"),
        ("Imp_IssueEnumCase", "Enum casing normalized", "枚举大小写已规范化"),
        ("Imp_IssueEnumMismatch", "{0} is not one of the allowed values", "{0} 不在允许的取值内"),
        ("Imp_IssueParse", "Invalid JSON", "JSON 解析失败"),
        ("Imp_IssueSchema", "{0} violates the validation rules", "{0} 不符合验证规则"),
    ];
}
