namespace VelaShell.Plugin.Mongo;

public sealed partial class Loc
{
    /// <summary>集合工作台:网格 / 树 / JSON 三视图、筛选栏、文档检查器、暂存区与分页。</summary>
    private static readonly (string Key, string En, string Zh)[] CollectionTexts =
    [
        // ── 工具行 ──
        ("Cw_AddDocument", "Add document", "添加文档"),
        ("Cw_Clone", "Clone", "克隆"),
        ("Cw_Import", "Import", "导入"),
        ("Cw_Export", "Export", "导出"),
        ("Cw_CopyJson", "Copy as JSON", "复制为 JSON"),
        ("Cw_ViewGrid", "Grid", "网格"),
        ("Cw_ViewTree", "Tree", "树"),
        ("Cw_ViewReadOnly", "Views are read-only — edit the source collection instead.", "视图是只读的 —— 请到源集合里修改。"),
        ("Cw_ViewBannerTitle", "View · read-only", "视图 · 只读"),
        ("Cw_ViewBanner", "Computed by a pipeline over {0}; documents cannot be edited here.", "基于 {0} 的管道计算而来,这里不能编辑文档"),
        ("Cw_IdImmutable", "_id cannot be changed — clone the document instead.", "_id 不能修改 —— 需要换 _id 请克隆一份。"),

        // ── 查询栏 ──
        ("Cw_Filter", "Filter", "筛选"),
        ("Cw_Find", "Find", "查找"),
        ("Cw_Reset", "Reset", "重置"),
        ("Cw_History", "History and favorites", "历史与收藏"),
        ("Cw_HistoryEmpty", "No filters yet", "还没有筛选历史"),
        ("Cw_Favorite", "Star this filter", "收藏这个筛选"),
        ("Cw_Projection", "Projection", "投影"),
        ("Cw_Sort", "Sort", "排序"),
        ("Cw_Skip", "Skip", "跳过"),
        ("Cw_Limit", "Limit", "限制"),
        ("Cw_Hint", "Index hint", "索引提示"),
        ("Cw_HintAuto", "Auto", "自动"),
        ("Cw_Explain", "Explain", "执行计划"),
        ("Cw_FilterSyntax", "Filter syntax error", "筛选语法错误"),
        ("Cw_FixHint", "Alt+↵ fix", "Alt+↵ 修复"),

        // ── 底栏 ──
        ("Cw_AddRow", "Add a row (staged)", "新增一行(暂存)"),
        ("Cw_DeleteRows", "Delete selected (staged)", "删除选中(暂存)"),
        ("Cw_ApplyTip", "Apply pending changes (Ctrl+S)", "应用待提交的修改(Ctrl+S)"),
        ("Cw_DiscardTip", "Discard pending changes (Esc)", "放弃待提交的修改(Esc)"),
        ("Cw_StopTip", "Stop the running query (killOp)", "停止正在运行的查询(killOp)"),
        ("Cw_PendingNone", "No pending changes", "没有待提交的修改"),
        ("Cw_PendingPrefix", "Pending: ", "待提交："),
        ("Cw_PendingEdits", "{0} modified", "{0} 修改"),
        ("Cw_PendingInserts", "{0} new", "{0} 新增"),
        ("Cw_PendingDeletes", "{0} deleted", "{0} 删除"),
        ("Cw_PendingDocs", "Pending: documents {0} · {1} changes", "待提交：文档 {0} 共 {1} 处修改"),
        ("Cw_PendingKeys", "Ctrl+S apply · Esc discard", "Ctrl+S 应用 · Esc 放弃"),
        ("Cw_HideSidePanel", "Hide the right panel", "隐藏右侧面板"),
        ("Cw_ShowSidePanel", "Show the right panel", "显示右侧面板"),
        ("Cw_PageCount", "/ {0} pages", "/ {0} 页"),
        ("Cw_PageCountUnknown", "/ … pages", "/ … 页"),
        ("Cw_Status", "{0} · {1} rows · {2} ms", "{0} · {1} 行 · {2} ms"),
        ("Cw_StatusPending", "{0} pending", "{0} 项待提交"),
        ("Cw_CopiedDocs", "Copied {0} document(s)", "已复制 {0} 份文档"),

        // ── 检查器 ──
        ("Cw_Document", "Document", "文档"),
        ("Cw_TabFields", "Fields", "字段"),
        ("Cw_TabInfo", "Collection", "集合信息"),
        ("Cw_FieldMissing", "—  field not present", "—  字段不存在"),
        ("Cw_TypeMissing", "Missing", "缺失"),
        ("Cw_AddField", "Add field", "添加字段"),
        ("Cw_ApplyChanges", "Apply changes", "应用修改"),
        ("Cw_NoValidator", "No $jsonSchema validation rule", "未设置 $jsonSchema 验证规则"),
        ("Cw_SchemaOk", "Passes the $jsonSchema validation rule", "符合 $jsonSchema 验证规则"),
        ("Cw_SchemaViolations", "{0} validation issue(s): {1}", "{0} 处不符合验证规则：{1}"),
        ("Cw_ChangeType", "Change type", "修改类型"),
        ("Cw_InfoNamespace", "Namespace", "命名空间"),
        ("Cw_InfoKind", "Kind", "形态"),
        ("Cw_InfoViewOn", "View on", "源集合"),
        ("Cw_InfoCount", "Documents", "文档"),
        ("Cw_InfoSize", "Data size", "数据大小"),
        ("Cw_InfoAvg", "Average document", "平均文档"),
        ("Cw_InfoStorage", "Storage", "存储大小"),
        ("Cw_InfoIndexes", "Indexes", "索引"),
        ("Cw_InfoCapped", "Capped size", "固定集合上限"),
        ("Cw_InfoValidator", "Validation", "验证规则"),

        // ── 添加字段 ──
        ("Cw_AddFieldTitle", "Add field", "添加字段"),
        ("Cw_AddFieldRoot", "top level", "顶层"),
        ("Cw_AddFieldName", "Name", "字段名"),
        ("Cw_AddFieldType", "Type", "类型"),
        ("Cw_AddFieldValue", "Value", "值"),
        ("Cw_AddFieldValueHint", "Empty = {0}", "留空 = {0}"),
        ("Cw_AddFieldConfirm", "Add", "添加"),
        ("Cw_AddFieldBadName", "Field names cannot be empty, start with $ or contain a dot.", "字段名不能为空、不能以 $ 开头、不能含点号。"),
        ("Cw_AddFieldExists", "That field already exists.", "这个字段已经存在。"),

        // ── 右键菜单 ──
        ("Cw_MenuEditValue", "Edit value", "编辑值"),
        ("Cw_MenuChangeType", "Change type", "修改类型"),
        ("Cw_MenuAddField", "Add field", "添加字段"),
        ("Cw_MenuAddFieldEllipsis", "Add field…", "添加字段…"),
        ("Cw_MenuInsertElement", "Insert element into array", "在数组中插入元素"),
        ("Cw_MenuCopyValue", "Copy value", "复制值"),
        ("Cw_MenuCopyPath", "Copy path", "复制路径"),
        ("Cw_MenuCopyJson", "Copy as JSON", "复制为 JSON"),
        ("Cw_MenuFilterBy", "Filter by this value", "按此值筛选"),
        ("Cw_MenuOpenQuery", "Open in new query", "在新查询中打开"),
        ("Cw_MenuOpenEditor", "Edit in document editor", "在文档编辑器中编辑"),
        ("Cw_MenuSetNull", "Set to null", "设为 null"),
        ("Cw_MenuDeleteField", "Delete field", "删除字段"),
        ("Cw_MenuDeleteDoc", "Delete document", "删除文档"),
        ("Cw_MenuDrill", "Open as table", "展开查看"),
        ("Cw_MenuDeleteElement", "Delete element", "删除元素"),
        ("Cw_MenuUndelete", "Undo delete", "撤销删除"),
        ("Cw_MenuFilterPreview", "Filter:", "筛选将生成"),

        // ── 树视图 ──
        ("Cw_TreeKey", "Key", "键"),
        ("Cw_TreeValue", "Value", "值"),
        ("Cw_TreeType", "Type", "类型"),
        ("Cw_TreeOriginal", "was {0}", "原值 {0}"),
        ("Cw_TreeAdded", "new", "新增"),
        ("Cw_AutoId", "(auto)", "(自动生成)"),
        ("Cw_EmptyObject", "(empty object)", "(空对象)"),
        ("Cw_ItemCount", "{0} items", "{0} 项"),

        // ── 网格钻入(双击对象 / 数组单元格)──
        ("Cw_DrillValue", "value", "值"),
        ("Cw_DrillArray", "Array · {0} items", "数组 · {0} 项"),
        ("Cw_DrillObject", "Object · {0} fields", "对象 · {0} 个字段"),
        ("Cw_DrillDoc", "Document #{0}", "文档 #{0}"),
        ("Cw_DrillNewDoc", "New document", "新文档"),
        ("Cw_DrillBack", "Back (Backspace)", "返回上一层(Backspace)"),

        // ── JSON 视图 ──
        ("Cw_CardEdit", "Edit", "编辑"),
        ("Cw_CardFormat", "Format", "格式化"),
        ("Cw_CardRevert", "Revert", "撤销"),
        ("Cw_CardUpdate", "Update document", "更新文档"),
        ("Cw_CardMeta", "· {0} · {1} fields", "· {0} · {1} 个字段"),
        ("Cw_CardEditing", "Editing · {0} change(s)", "编辑中 · {0} 处修改"),
        ("Cw_CardCaret", "Ln {0}, Col {1} · {2}{3}", "Ln {0}, Col {1} · {2}{3}"),
        ("Cw_SyntaxShell", "Shell syntax", "Shell 语法"),
        ("Cw_SyntaxJson", "Extended JSON", "扩展 JSON"),
        ("Cw_SyntaxOk", "Syntax OK", "语法正确"),
        ("Cw_SyntaxOkSchema", "Syntax OK · passes validation", "语法正确 · 符合验证规则"),
        ("Cw_SyntaxError", "Syntax error", "语法错误"),
        ("Cw_FoldItems", "…{0} items", "…{0} 项"),
        ("Cw_MarkModified","Modified · was {0}", "已修改 · 原值 {0}"),
        ("Cw_MarkAdded", "New field", "新增字段"),
        ("Cw_MarkRemoved", "Removed {0}", "已删除 {0}"),
        ("Cw_Outline", "Outline", "大纲"),
        ("Cw_OutlineDoc", "Document #{0}", "文档 #{0}"),
        ("Cw_Display", "Display", "显示"),
        ("Cw_TypeHints", "Inline type hints", "行内类型提示"),
        ("Cw_FormatOnSave", "Format before saving", "保存前自动格式化"),
        ("Cw_Shortcuts", "Editing shortcuts", "编辑快捷键"),
        ("Cw_KeyComplete", "Field / value completion", "字段 / 值补全"),
        ("Cw_KeyMove", "Move field", "移动字段"),

        // ── 补全 ──
        ("Cw_SuggestHeader", "Value suggestions {0} · sampled {1} documents", "值建议 {0} · 抽样 {1} 份文档"),
        ("Cw_SuggestRatio", "{0}%", "分布 {0}%"),
        ("Cw_SuggestFooter", "↑↓ select · Tab accept · Esc close", "↑↓ 选择 · Tab 接受 · Esc 关闭"),
        ("Cw_SuggestField", "field · {0}", "字段 · {0}"),
        ("Cw_SuggestFieldDetail", "Present in {0} of {1} sampled documents.", "抽样的 {1} 份文档里有 {0} 份带这个字段。"),
    ];
}
